<a href="https://colab.research.google.com/github/nikhilreddi02/SentEmbLog/blob/main/AmazonSentLog.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
df = pd.read_csv('AmazonReview.csv')

In [ ]:
df

                                                  Review  Sentiment
0      Fast shipping but this product is very cheaply...          1
1      This case takes so long to ship and it's not e...          1
2      Good for not droids. Not good for iPhones. You...          1
3      The cable was not compatible between my macboo...          1
4      The case is nice but did not have a glow light...          1
...                                                  ...        ...
24995  These cables (lightning) are far superior to m...          5
24996  This unit performs exactly as advertised.  I u...          5
24997  I had the key cut at a local hardware store cu...          5
24998  I love my case I ordered from amazon. It wasn'...          5
24999  Awsome!!! I loved this little speaker. It has ...          5

[25000 rows x 2 columns]

In [ ]:
df['Sentiment'].value_counts()

Sentiment
1    5000
2    5000
3    5000
4    5000
5    5000
Name: count, dtype: int64

In [ ]:
df['Sentiment'] = df['Sentiment'].apply(lambda x : 1 if x > 3 else 0)

In [ ]:
stop_words = stopwords.words('english')

In [ ]:
df['Review'] = df['Review'].astype(str).apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

In [ ]:
df['Review'].head()

0    Fast shipping product cheaply made I brought g...
1    This case takes long ship even worth DONT BUY!!!!
2    Good droids. Not good iPhones. You cannot use ...
3    The cable compatible macbook iphone. Also conn...
4    The case nice glow light. I'm disappointed pro...
Name: Review, dtype: object

In [ ]:
X = df['Review'].tolist()
X

['Fast shipping product cheaply made I brought grandchild IPod would protected fell skin suitable protection. It good decoration. Therefore I rated it1*',
 'This case takes long ship even worth DONT BUY!!!!',
 'Good droids. Not good iPhones. You cannot use features watch iPhone synch iPhone',
 'The cable compatible macbook iphone. Also connector came apart cables started fraying.',
 "The case nice glow light. I'm disappointed product meet advertisement.",
 'The cable keeps coming message accessory supported. I bought specifically I led believe totally compatible iphone 5s. I able charge iphone either cables. II throw trash. It waste money,',
 'This pos broke phone 3 uses I luckily able pull remnants tweezers. Stay. Away.',
 'This product suck hard 2 hear wat saying',
 "Music cuts within 30 secs. I like Aukey's product one really disappointed me! Aukey needs go back drawing board ...",
 'Yeah say mirror screen mean - iPod becomes like $150 mirror nearly impossible see actual screen direct sunlight.',
 "No power AC adapter. Tried several outlets. I confirmed USB cable worked. Just wall adapter didn't. I'm returning it. May shell Apple brand one, much hurts.",
 "Purchased product vendor Outlet. Bought listen cd's used less 10 times. Decided use recently cd player skips tracks malfunctioning. I contacted seller showed little concern product work. Told contact manufacturer. Should gone Sony.<br /><br />DO NOT MAKE THE MISTAKE AND BUY THIS PIECE OF CRAP. YOU PAY FOR WHAT YOU GET. YOU PAY FOR NO NAME AND YOU GET NO QUALITY!!!!!",
 'It Tedious get thing work look good, need know tricks trade work.',
 'Like others I fooled initial customer reviews product. They either outright lies placed product seller generate sales. DO NOT BUY THIS PRODUCT. The way I describe adds mirror finish kindle. This product going straight garbage can. Full stop',
 'Give one star I recieved timely fashion I dissatisfied !!!!! Unit work returned.',
 'The charger stopped working three weeks use. The light still comes everything, charge anything',
 'This device sold different names marketplace. I bought version local Radio Shack preparation upcoming road trip. From moment I picked box I skeptical, turns I right. The box light I thought empty. When I opened (before leaving store make sure actually contained product!) I saw indeed there, lightweight. Not wanting judge, I took home installed it. The good: installed quickly easily Acura MDX. The bad: I put iPad in, immediately obvious mount arm WAY flimsy support weight iPad. I encounter slipping ball joint (that adjusts angle) mounts headrest - held. However, whole arm flimsy resulting something almost broke brushing it. The pad flops around arm bends wiggles like going break. And terms usability, pad bounces around arm much anything smooth interstate, son cried \\\\"Please turn off!\\\\". This went back box going back store. It\'s worth $15, much less costs.',
 'It cute',
 "It seemed like great deal! But reality set quick. Not user friendly mp3 player, option lock buttons mode button broke 1 week!! Never again!! I'll get another Coby pay little last A LOT longer!!",
 'Ready compatibility lead believe compatible 3GS phones. The wires work old cube, plugged cubes, phones (2) tell compatible device.',
 "This product failed work Garmin. Garmin would boot up. The old battery still use little holding power fortunately still works.<br /><br />This replacement fails work. I suspect software detecting non-Garmin battery prevents working...that's theory. Don't Buy.",
 'This product worked three minutes. Sometimes would turn on, even then, played songs one time, stopped playing. Also, compatible Rhapsody service. I recommend.',
 'Well disappointed waited almost full month find lost mail item stock never received it. But fully refunded right away discovered.',
 'stopped working one week. company refused replace',
 '500watts expected average 50watts rms..it metal ,so looked nice..but sounds like crap... sorry prefer buy, pieso tweeter . sound clean....i use them...i use, motorola, seleniun,and audio pipe tweeters',
 'I bought couple years ago, started problem screen auto dimmer thing effective. Then recently, problem came up. I tried take CD I put in, CD player mechanism broken. I literally pry thing open get CD out, then, course, broken. Thankfully speakers good, I new stereo accompanying ones... waste money',
 "This lasted 45 days. The MP3 player never worked well-erased songs player I hooked up. But I overly concerned I bought play CD's. But 40days recognize CDRs week later stopped recognizing CDs kind. I contacted seller dud ofcourse got nowhere past 30 day warranty. I tried contact manufaturer, cost ship item worth. Garbage garbage garbage!!!!!",
 'I felt deceived, I though actually case iPod. In titles advirtiament mentioned stick on, non protective',
 'This damaged fast use caution have, scam',
 'Extremely un-happy speakers gotten replacing blew 2000 mustang. old busted broken speakers bass these. sure inexpensive get less payed for.',
 'The headset damaged would work.<br />They appear used due eat wax located earbuds.<br />Not good item',
 "I expecting case two pieces snap together, like pretty much every similar case I've encountered. This piece hard plastic snaps onto back player -- front screen completely unprotected!",
 'This product title lists fitting TomTom GPS 4.3 screen. I purchased exact case TomTom GPS 4.3 screen, way GPS fits case. I happy product, small!!!',
 'I bought item security job worked first two days stopped working correctly. The speaker mic transmit radios receive transmissions back. It waste $59.00. I bought motorola radius cp200 radio even work anymore. This worth money.',
 "Didn't fit right...was waste money...should adked refund bother.",
 'So ordered 3 chargers surprisingly, dont work. It charge phone useless. Seller running scam selling garbage products.',
 'No instructions info best way install them. Cut rough messy. After clean modifying work',
 'useless ticks fallin dead dog. Have able use since I purchased',
 'I used watch various functions. The time accurate, kept losing seconds would end several minutes behind.<br />The tempurature seemed accurate time.<br />The Timer stopwatch functions worked well<br />the printing function wore within 2 months use 3 months battery died display went out.',
 'Do buy it!!! Does work all!! Called company got run around 4 weeks I got refund! Aweful product aweful company deal with!!!',
 'The quality product disappointing. The purple color began chipping one day use.',
 "unfortunately I found position I needed new security Mic work figured ide give try due trust Amazon sellers.. sellers service expected, unfortunately quality product sub par. one work right box. Mic would randomly key, ( broadcast button depressed) ear piece sounds quality better expected tho... Mic niether reliable even mildly functional, I can't recommend product, fact avoided Mic needs even slightly important..",
 'This Ipod armband holder poorly made. The \\\\"velcro\\\\" adjustment things armband simply glued ripped I ever got chance use it. My ipod fit properly I would liked either. The product simply junk I never got use it. It came apart simply trying adjust arm. I guess get pay for.',
 'Well, I bought armband replace older one. I hardly used 5 times since I bought it-I prefer older one, thought I would start using one everyday gave out. My older brand name ipod band still ok shape even beginning fray. And brand new one piece junk already falling apart. Guess brand names matter reason.',
 'I bought GPS return match dashboard 2008 Toyota Camry.<br />They shipped different color displayed amazon.when I emailed simplesoft confirmed product available one color, different picture displayed here. Product shipped dark grey color. I match dashboard toyota camry.',
 "I got thing wife could play car system. I loaded couple songs day I got worked okay. It felt cheap flimsy seemed function fine. I serious health problem come next day forgot thing weeks. Yesterday I went rip wife's favorite songs put player. Ten minutes process I start getting &#34;card error&#34; message player thing vanishes far computer concerned. Took memory card cleaned contacts reinserted, luck. Every jiggle card slot work seconds quit again. But hey, radio still works! Too late send back Amazon 16 bucks I guess I'll eat go on. You get pay case. An MP3 player 16 dollars sounds good true is. Cheap piece junk.",
 "Unfortunately delicate. I'm careful cables I want last. I used adapter 6 times quit working. Original iPhone 5 cable still going strong.",
 "I charger plugged car couple months. It sporadically working. It would work phone (HTC) ipad. Only one usb side would work time. It mainly used kids ipods big deal run replace lived it. Last week charger started smoke spark dashboard. Luckily happened I pulling driveway. The outlets get power car turned on, I able turn car run house grab pliers screwdriver pull melted charger outlet. I unable pull hand small sat far outlet nothing grab onto fingers. I would definitely recommend charger anyone. It's worth risk.",
 "These poorly made! I excited I saw good reviews headphones. I disappointed! After first week plug started breaking. The sound quality poor. I bought mic I actually use phone call person I'm talking barely hear background noise. I even want write making mad again! Save money try something else!",
 'I ordered 9ft Lightning Cable. I say nice long cable, cable useful jump rope comes charging phone. I plugged charged phone one night worked perfectly. The next day I plugged phone nothing happened, I took cable charger plugged PC still nothing, I disconnected cable phone. As soon I disconnected cable connector felt loose. The cable proceeded separate Lightning connector. I uploaded picture customer images. On side note, cable also much stiffer OEM cable. I able return, would recommend cable.',
 "says box employee barns noble informed DO NOT put screen protector nook simple touch glowlight comes preinstalled one factory. ruin screen. i'de probobly take item sale inventory.",
 "Don't bother buying. I 3rd generation ipod touch charger charge it. It says compatible.",
 'mine set Ukrainian. user manual tells 12 languages change company tells check user manual. I guess I need hire Ukrainian drive around read it.',
 'It definitely looks like lot stuff 9.99 + shipping. The problem work well try press butttons Creative Zen Vision M. Because silicon case tight around zen press button allow click release loosen case click releases. I received yesterday I dont know case loosen little long run I definitely recommend this.',
 'These really cute. I thought would super gift 3 year old granddaughter. BUT, way complicated use My grown daughters 11yr old grandson trouble using also.',
 'Did function properly. Use unit saem maufacturesr wonderful. I really understand unit work?',
 "Okay, I mp3 player, think it. It holds maybe fifteen songs. A 512mb iPod shuffle holds 120 songs, divide 512 8 get 64 divide 120 8 get fifteen! It's almost funny... fifteen songs",
 "The video quality makes camera worthless. When charged small incomplete pamphlet instructions states supposed show charging icon. Instead another screen startup covers charging icon. This built defect. I attempted numerous times get icon appear including using factory reset icon. The battery rapidly discharges, short battery life. There bubble wrap top, opened laying there, without thing it, indicates already opened returned. Trying return essentially response Anleo, supposed company selling it, help, contacting another company. It less Chinese double talk broken English, stating someday refund given sending back, help. It less refusal give refund within Amazon's stated refund policy. I contacted Amazon filed complaint pending. This buyer beware. I found video car cam totally worthless aspects. And far seller company located, appears China, pretends make refunds. I spoken many times Amazon's customer service excellent. I hopes seller removed Amazon.com . They making Amazon.com look bad addition selling worthless product NOT abiding Amazon's return policy.",
 "I bought recently exchanged another. Neither worked properly. Both units failed record actual mileage. I standard 3 mile running route. I set unit detailed instructions, times mileage end run - 1.5 miles first unit 2.1 miles second. When I tried calibrate linking computer, software said runs 'walks' discrepancy outside margin error. So unreturned units un favor Garmin GPS watch (Forerunner 110) works perfectly lot less fuss shoe sensor required.",
 "I really like product.Seller great dthe shipping fast. The speakers'sound great. The main reason buy product take us camping. However, specifications says charges Ipods. We Ipod Classic Ipod touch charge even playing. I called company twice, service terrible. No one answered. If anyone knows charge Ipod I appeciate instructions I can't find even online. Thanks.",
 'dead arrival',
 'The setup pain. The instructions clear.<br />The product extremely buggy car charger didnt work',
 'sporadic works not. times bars go normally short lived. still issues calls dropping.',
 "I used item third time today. It longer charge phone. I get message phone device consistently compatible phone. I still play music vehicle's system, using phone's gps app music app battery drains quickly. This thing basically useless without charging ability. And late get refund.",
 'I bought three new SanDisk players last six years.<br />All went hell two years.<br />Never SanDisk player!',
 "I ordered lasonic i931x two weeks ago, I received today doesnt work! Read instructions trouble shooting anything. Or least helps. I plugged many working electrical sockets juice work all. Won't turn on, nothing. Even av/out slot back even hoe plug printed plastic w hook ups all. Did I buy display shell something? Wtf!",
 'This review Pioneer AVH-P8400. Unfortunately, really positive purchase. I honestly say I pretty disappointed Pioneer head unit. I hoping Pioneer gets issues straightened fixed firmware update.<br /><br />First, positive:<br />-This unit really sounded much better previous Pioneer Premier F90BT. There notable clarity I switched it.<br />-I connect two ipods rather one.<br />-The G.U.I. also appealing.<br />-Not bunch harnesses back unit also plus made installation lot easier.<br />-Most issues head unit appear software based, hopefully fixed soon<br />-The screen vivid clear resolution. It definitely one nicer screens I seen.<br />-Very quick load time. Unit ready go seconds turning car on.<br /><br />The Negative:<br />-The screen goes dead respond touches intermittently. Considering many features controlled touching screen, bad deal.<br />-If using iphone, iphone alert sound effects come though listening Pandora ipod feature iphone. Im sure head unit issue iphone issue, driving music annoying.<br />-The GPS apps garbage. PERIOD.<br />-If connect iphone Bluetooth connects, causes sorts problems. The Pandora feature work, use AppRadio order hear Pandora, AppRadio also function properly. If turn car reason, disconnect iphone restart it, Bluetooth connects iphone already connected head unit, mentioned problems.<br />-The CD-IU201S Cable ridiculously short. The part cable connects iphone sadly 2 feetlong, means mount iphone close unit. I bought Iphone extension caused AppRadio longer function. Ridiculous.<br />-My ipod locks least 6-10 times week head unit. When I check ipod disconnected it, still pioneer logo order get working restart.<br />-This unit produces insane amount noise (hissing). Its audible listening music unit nothing selected source.<br /><br />ALSO!!! Pioneer aware issues unit, intention releasing firmware update fix it. Basically, own. This unit brought better standard is, unlike pioneer units past recieved firmware updates fix problems issues.<br /><br />Im really saddened unit. I loyal pioneer customer many years. I gone 8 Units terrible. I wanted replace F90BT something newer faster, precise GPS. I originally considering AVIC-Z140BH, I really like I would disconnect ipod connect iphone use certain features. I accustomed connecting ipod, music it, head unit putting glove box messing anymore. I hoping iphone apps car. You use iphone control iphone apps, exception Pandora. This dangerous keep taking eyes road this, mention clumsy short cable causing problems reach.<br /><br />I say head unit great. major downside iphone/ipod controls appmode. also whole wait till bluetooth connects also annoying. wrong turn car try again.<br /><br />UPDATE -I longer able find much positive purchase. Last night driving unit began volume issues connected iPhone. It also issues iPhone playing music OVER ipod selected. Even pressing mute issue resolved, music continued play blaring. I longer partially satisfied purchase considering purchasing another one getting rid one. It helpful.',
 'After receiving item cut vehicle, I took Volvo dealer unable program them. I purchased new fobs dealer programmed today. Not success. I would caution anyone using OEM fobs - make sure Volvo dealer able program them!',
 "This camera kit deserve one star. I received package part missing. I contacted seller got missing part mail. After one month use car camera stopped working apparent fixable reason (it's still broken). The unit got mixed reviews (practically bad) time I decided buy. I listened. The old adage get pay applies here.",
 "I received unauthentic item seller Bokit. It unfortunately one many &#34;fake&#34; versions popular camera. It comes inferior Novatek NT96220FG chip instead actual chip advertised item page. This chip much lesser quality. It easy spot fake version item simply recording short video clip seeing format camera saves as. If .MOV authentic, .AVI fake item. I received one latter. You also check specs video file simple video editing program see quality video less specs original version item.<br /><br />My item came orange box I read already reported many others forums Dashcamtalk forums ones carrying fake units. Amazon needs try little harder verify integrity sellers let anyone sell whatever wish grandma's basement. Sellers, responsibility check item insure authentic. Now I waste time money driving UPS return try luck another seller.",
 'I purchased mount motorcycle quite disappointed. I mounted bracket handlebar attached TomTom One XL it. I discovered ball socket mount pops easily. I glad I get road GPS would surely come bike slightest bump road I would GPS dangling power cord best. Its inexpensive reason.',
 'Upon receiving item I plugged phone charge it. After seconds charge little message came across screen stating cable accessory certified may work reliably IPhone. It yet able charge phone.<br /><br />I DO NOT RECOMMEND BUYING THIS ITEM',
 "Matt Geyster BaseOne Labs owes $24,000.00 refunds people purchased product him;<br />product created fake video fake proto-type use promotion;<br />product repeatedly promised deliver;<br />product then, finally, admitted, never existed never would exist know manufacture it;<br />refunds promised deliver, months months months months later, still not...and outright refuses respons owes money, product.<br /><br />If purchase product guy company, count never receiving support, response problems poor quality missing shipments.<br /><br />Don't believe products described sales materials, claims make performance said products.<br />They amply demonstrated incompetence managing manufacture product redeeming use value,<br />as well deliberately lied entire group customers. And lied again. And lied lied.<br />And promised make good lied. Which, course, another lie.<br /><br />If give money product, expect position honor warrantees, returns, product support.<br />Your money, given Matt Geyster BaseOne Labs gone, baby, gone.",
 'Junk charge nothing .',

In [ ]:
from sentence_transformers import SentenceTransformer
embedding = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2').encode(X)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [ ]:
embedding.shape

(25000, 384)

In [ ]:
Y = df['Sentiment'].tolist()

In [ ]:
Y[0]

0

In [ ]:
X_train,x_test,Y_train,y_test = train_test_split(embedding,Y,test_size=0.2,random_state=42,stratify=Y)

In [ ]:
log = LogisticRegression()

In [ ]:
log.fit(X_train,Y_train)

LogisticRegression()

In [ ]:
ypred = log.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,ypred))

0.7726

In [ ]:
sent = ['I dont the product because it was too high but not at all usefull ']
sent_embedding = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2').encode(sent)
ypred = log.predict(sent_embedding)
print(ypred)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

[0]

In [ ]:
sent_embedding.shape

(1, 384)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train,Y_train)

RandomForestClassifier()

In [ ]:
ypred = rf.predict(x_test)
print(accuracy_score(y_test,ypred))
#

0.7262